# 2020-06-15 (月)

## Graphene: `Exception: Int cannot represent non 32-bit signed integer value: -2664960385504480382`

~~~py
Traceback (most recent call last):
  File "/home/vagrant/.anyenv/envs/pyenv/versions/reform2/lib/python3.8/site-packages/graphql/execution/executor.py", line 480, in complete_value_catching_error
    completed = complete_value(
  File "/home/vagrant/.anyenv/envs/pyenv/versions/reform2/lib/python3.8/site-packages/graphql/execution/executor.py", line 563, in complete_value
    return complete_leaf_value(return_type, path, result)
  File "/home/vagrant/.anyenv/envs/pyenv/versions/reform2/lib/python3.8/site-packages/graphql/execution/executor.py", line 626, in complete_leaf_value
    serialized_result = return_type.serialize(result)
  File "/home/vagrant/.anyenv/envs/pyenv/versions/reform2/lib/python3.8/site-packages/graphql/type/scalars.py", line 31, in coerce_int
    raise Exception(
Exception: Int cannot represent non 32-bit signed integer value: -2664960385504480382

~~~

- python の `hash()` の 整数が大きすぎでJSONにシリアライズできない
